### ISSUE TITLE
do it like the kernel

### ISSUE THREAD

**Issue by iofo** [MengRao/tscns#6]
What do you think of this to overcome NTP issues:

A process which opens a shared memory segment and recalibrates periodically using syncTime and writes the base_ns and base_tsc and ghz to the shared memory segment.  A process can then use rdtsc and read the base_ns and base_tsc and GHZ from the shared memory to compute the timestamp.  This in fact replicates the kernel VDSO setup but we can use a finer grained ghz value.  It has the advantage that we are more closely tracking wall clock so we don't drift over time due to NTP slewing.  My problem is the NTP drift as this tscns currently does it and I don't want to recalibrate in my fast path.
Any flaws in this approach?

**Comment by iofo** [comment]
actually its not NTP problems its just error accumulation.
this is much more stable
uint64_t tsc2ns(uint64_t tsc) const { return base_ns + (int64_t)((int64_t)(tsc-base_tsc) * tsc_ghz_inv); }
than:
uint64_t tsc2ns(uint64_t tsc) const { return ns_offset + (int64_t)((int64_t)tsc * tsc_ghz_inv); }

**Comment by MengRao** [comment]
I tried the "uint64_t tsc2ns(uint64_t tsc) const { return base_ns + (int64_t)((int64_t)(tsc-base_tsc) * tsc_ghz_inv); }" with test.cc and it had the same performance as the original one.  Error accumulation is due to tsc hz not being that precise, although cheat program can get the kernel tsz hz at boot time but it can be changed by NTP afterwards.

So my suggestion is, don't compare rdns() with system time as it drifts. It's more suitable to measure a time span with a diff of two rdns().

**Comment by iofo** [comment]
Ok thanks.
Yes upon further investigation I see what you say is correct.
Do you happen to know if clock_gettime is still a problem for being slow on
modern kernels and cpus? Because I found that if I remove the sleep in
test.cc all the timings come way down so potentially the slowness is due to
cache miss on vdso page but when you spin and  repeated call it then it’s
hot. I also task set to a core for this test.
On my machine with the sleep the a2b was order of few hundred nanos. But
with no sleep it went down to about 20 nanos.

Thanks for your work in this area very interesting project.
